language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION=1.5

install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install coverage

script: coverage run quicktest.py djfaker

after_success:
 - pip install coveralls
 - coveralls
